#!/usr/bin/env python

# Shell module to execute
import sys
import json
import os
import subprocess

params = json.loads(sys.stdin.read())


# Params for this module
# chdir: cd into the given directory to execute the shell command
# shell: The shell to use, by default it's /bin/sh
# cmd: The command to run. Wrapped by quotes if there are spaces
# loglevel: if debug, it shows you the entire output as part of 'output' key
result = {}
try:
    shell = params.get("shell", "/bin/sh")
    cmd   = params.get("cmd")
    if not cmd:
        raise Exception("Required parameter 'cmd' not found")
    chdir = params.get("chdir")
    # FIXME: Error out if chdir cannot be stat'd
    if chdir:
        os.chdir(chdir)
    shell_args = ["%s" % shell, "-c", "%s" % cmd]
    p = subprocess.Popen(shell_args, stdout=subprocess.PIPE,stderr=subprocess.PIPE)
    output, err = p.communicate()
    if err:
        raise Exception(err)
    result["status"] = "changed"
    if 'loglevel' in params and params['loglevel'] == 'debug':
        result["output"] = output
    result["msg"] = "Successfully exec'ed command"
except Exception as e:
    result["status"] = "error"
    result["msg"] = str(e)
print json.dumps(result)
