#!/usr/bin/env python
import sys
import json
import os
import subprocess

params = json.loads(sys.stdin.read())

# file is already copied if it comes till here
#
result = {}
try:
    f = params.get("file","")
    l = params.get("line", "")
    if not f:
        raise "Missing file"
    if not l:
        raise "Missing line"
    source = open(f)
    lines = source.readlines()
    source.close()
    lines.append(l + "\n")
    destination = open(f, "w")
    for l in lines:
        destination.write(l)
    destination.close()
    result["status"] = "changed"
    result["msg"] = "Appended line"
except Exception as e:
    result["status"] = "error"
    result["msg"] = str(e)

print json.dumps(result)
             
