#!/usr/bin/env python
# copy module
# Copies a file over to the node over a given transport
# This module is a special case and the bulk of the work is done
# in the henchman engine. This module however ensures that the permissions
# are satisfied
# Params for this module
# owner: The owner of the file (optional)
# group: The group of the file (optional)
# mode:  The file mode (default: 644)
# dest:  The destination (required)

import sys
import json
import os
import subprocess
import pwd

params = json.loads(sys.stdin.read())

result = {}
try:
    owner = params.get("owner",pwd.getpwuid( os.getuid() ).pw_name)
    group = params.get("owner",pwd.getpwuid( os.getuid() ).pw_name)
    mode = params.get("mode","0644")
    dest = params.get("dest")
    result["owner"] = owner
    result["group"] = group

    command = ["/bin/chown","-R","%s:%s" % (owner,group), "%s" % dest]
    p = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = p.communicate()
    if err != "":
    	raise Exception(err)

    command = ["/bin/chmod","-R","%s" % mode, "%s" % dest]
    p = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = p.communicate()
    if err != "":
    	raise Exception(err)
    result['status'] = "changed"
    result['msg'] = "State of file %s changed" % dest

except Exception as e:
    result["status"] = "error"
    result["msg"] = str(e)
print json.dumps(result)
