#!/usr/bin/env python
import sys
import os
import json
import subprocess
import json

# Params for this module
# url: url that provides the rpm that should be installed
# loglevel: if debug, it shows you the entire output as part of 'output' key
params = json.loads(sys.stdin.read())
result = {}
try:
    p = subprocess.Popen(["rpm", "-ivh", "%s" % params['url']], stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    output, err = p.communicate()
    
    if 'loglevel' in params and params['loglevel'] == 'debug':
        result['output'] = output
    
    if err != None:
        raise Exception(err)
    else:
        result['status'] = "changed"
        result['msg'] = "Successfully installed package %s" % params['url']

except Exception as e:
    result['status'] = "error"
    result['msg'] = str(e)
print json.dumps(result)
