#!/usr/bin/env python
import sys
import traceback
import os
import json
import subprocess
import json

# Params for this module
# url: url that provides the rpm that should be installed
# loglevel: if debug, it shows you the entire output as part of 'output' key
params = json.loads(sys.stdin.read())
result = {}
try:
    loglevel = params.pop("loglevel", "info")
    url = params.pop('url', None)
    if not url:
        raise "Missing required param 'url'"

    commands = ["rpm", "-ivh", url]
    replacepkgs = params.get("replacepkgs", False)
    if replacepkgs and replacepkgs in ["yes", "true", True]:
        commands.append("--replacepkgs")

    p = subprocess.Popen(commands, stdout=subprocess.PIPE,stderr=subprocess.PIPE)
    output, err = p.communicate()

    if err or p.returncode > 0:
      raise Exception(err)
    result['status'] = "changed"
    result['msg'] = "Successfully installed package %s" % url
    result['output'] = output

except Exception as e:
    result['status'] = "error"
    result['msg'] = "Error occurred while installing package %s" % url
    result['output'] = traceback.format_exc()
print json.dumps(result)
