#!/usr/bin/env ruby
require 'rubygems'
require 'json'
params = ''
while line = $stdin.gets
  params = JSON.parse(line)
end
result = {}
ls_result_with_error = ""
begin
  if params.keys.include?("chdir")
  	Dir.chdir params['chdir']
  end
  cmd = params["cmd"]
  env_params = params["env"] || ""
  env =  {}
  if env_params != "" 
    env_params.split(" ").each do |part|
      if part.include?("=")
        k,v = part.split("=") 	
        env[k] = v
      end
    end
  end  
  overall_cmd = [env, cmd.split(" "), :err =>[:child, :out]].flatten
  #chdir = params["chdir"]
  ls_result_with_error = ""
  IO.popen(overall_cmd) {|ls_io|
  	ls_result_with_error = ls_io.read
  }
  if $?.exitstatus != 0
  	result["output"] = {"stdout" => "", "stderr" => ls_result_with_error}
  else
  	result["output"] = {"stderr" => "", "stdout" => ls_result_with_error}
  end
  result["status"] = "changed"
  result["msg"] = "exec'ed command"
rescue Exception => e
  result["status"] = "error"
  result["msg"] = e
end
written = $stdout.write(result.to_json)
`echo #{written} > /tmp/shell_bytes`
#print result.to_json
