#!/usr/bin/env python
import sys
import json
import os
import subprocess

params = json.loads(sys.stdin.read())

# file is already copied if it comes till here
#
result = {}
try:
    owner = params.get("owner",pwd.getpwuid( os.getuid() ).pw_name)
    group = params.get("group",pwd.getpwuid( os.getuid() ).pw_name)
    mode = params.get("mode","0644")
    dest = params.get("dest")

    command = ["/bin/chown","-R","%s:%s" % (owner,group), "%s" % dest]
    p = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = p.communicate()
    if err != "":
    	raise Exception(err)

    command = ["/bin/chmod","-R","%s" % mode, "%s" % dest]
    p = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = p.communicate()
    if err != "":
    	raise Exception(err)
    result['status'] = "changed"
    result['msg'] = "State of file %s changed" % dest

except Exception as e:
    result["status"] = "error"
    result["msg"] = str(e)
print json.dumps(result)
