#!/usr/bin/env python
import sys
import os
import json

params = json.loads(sys.stdin.read())
print params

print "Installing package ", params["package"]

os.system("yum install -y %s" % params["package"])
